#!/usr/bin/env python3
"""Bandwidth-aware hint relabeling (coarse-grained, per-trace waste ratios).

Driver for the unified labeler (labeler.py): loads every data source the
labeling rules consume, assembles one CellData per (trace, bw) cell, and
emits hint bins via oracle_gen. All labeling logic lives in labeler.py;
this file owns I/O only.

Data (no new profiling sims needed):
  - ground_truth.jsonl per (trace, bw): per-PC AMAT for every prefetcher:degree
  - prefetch_stats.csv: per (trace, prefetcher_degree, bw) global counters + IPC
  - seg-sim outputs (optional 2nd pass): per-PC mixed-regime records

Tax terms (score="tax"):
  score(pc, pf:deg) = amat * (1 + lam_w*waste + churn_w*churn
                              + lam_i*ipc_gap + lam_l2*l2_gap)
    waste    = useless / demand        (absolute DRAM traffic per demand access)
    churn    = extra net issues vs the family's best-IPC degree, / demand
    ipc_gap  = 1 - ipc / ipc_best      (opportunity cost vs the trace's best policy)
    l2_gap   = hitrate_best - hitrate  (retired: real signal, failed as a
                                        per-PC linear tax - see labeler.py)

Usage:
  python3 relabel_hint_bw.py <bw_run_dir> <stage2_run_dir> <prefetch_stats.csv> \
      [cost_profile_dir] [seg_dir] [--schemes w,wci,pigougate] \
      [--config '{"lam_i":0.8}' [--config-name exp01]] [--list]
  Default (no options): regenerate the six historical bin sets
  (w, wc, wci, gate_t90, pigou, pigougate) byte-identically.
"""
import argparse
import csv
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ORACLE_GEN = os.path.join(HERE, "oracle_gen.py")

from labeler import (CANDIDATE_FAMILIES, GATE_FALLBACK, PRESETS, PARAM_SPACE,
                     DEFAULT_CONFIG, all_amats_tied, config_slug, is_candidate,
                     idx_to_key, make_labels, pigou_net, policy_to_stat_name,
                     CellData)

# Preset -> output bin name (gate_t90 keeps its historical name).
SCHEME_OUT = {"gate_t90": "hint_gate_t90.bin"}
# Presets that are not generated at native bandwidth (Scheme B reuses the
# 3200 label, so it only makes sense at a foreign target bw).
NO_3200 = {"gate_t90"}
# The six historical bin sets regenerated by default.
DEFAULT_SCHEMES = ("w", "wc", "wci", "gate_t90", "pigou", "pigougate")


def load_ground_truth(path):
    """pc -> {"best_prefetch","best_degree","all_amats"}"""
    out = {}
    if not os.path.isfile(path):
        return out
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            out[rec["pc"]] = rec
    return out


def load_waste(csv_path):
    """(trace, "ampm_d1", bw) -> waste ratio in [0,1]; 'no'/b0 -> 0

    Accuracy-based waste (1 - useful/issued): used by the GATE scheme,
    which thresholds on per-prefetch wastefulness.
    """
    waste = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            pf = r["prefetcher"]
            issued = int(r["pf_issued"])
            uhit = int(r["pf_useful_hit"])
            w = (issued - uhit) / issued if issued > 0 else 0.0
            waste[(r["trace"], pf, r["bw"])] = w
    return waste


def load_demand_total(profiling_dir):
    """Total demand accesses for the trace (policy-independent)."""
    if not os.path.isdir(profiling_dir):
        return 0
    for fn in os.listdir(profiling_dir):
        if not fn.endswith(".json"):
            continue
        tot = 0
        with open(os.path.join(profiling_dir, fn)) as f:
            for line in f:
                try:
                    tot += json.loads(line).get("access_count", 0)
                except json.JSONDecodeError:
                    pass
        return tot
    return 0


def load_traffic_waste(csv_path, demand_by_trace):
    """(trace, stat_name, bw) -> absolute-traffic waste = useless
    prefetches per demand access. Unlike 1-accuracy, this spreads
    policies apart on low-accuracy traces: dspatch on mcf ~ 1.3,
    sandbox ~ 0.6, stream ~ 0.05 — the tax can actually discriminate."""
    waste = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            dem = demand_by_trace.get(r["trace"], 0)
            w = int(r["pf_useless"]) / dem if dem > 0 else 0.0
            waste[(r["trace"], r["prefetcher"], r["bw"])] = w
    return waste


def load_churn(csv_path, demand_by_trace):
    """(trace, stat_name, bw) -> pipeline churn tax for degree selection.

    For each family, the degree with the best GLOBAL IPC is the reference
    (its extra issues are evidently productive). Any other degree pays a
    tax equal to its extra net-waste above the reference:
        [(issued - useful_hit) - (issued_ref - useful_hit_ref)] / demand
    This penalizes degree inflation only when the market (global IPC) has
    proven it net-harmful — cactusADM stream_d8 pays, soplex stream_d8
    (genuinely better than d1) pays nothing.
    """
    issued = {}
    hits = {}
    ipcs = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            dem = demand_by_trace.get(r["trace"], 0)
            key = (r["trace"], r["prefetcher"], r["bw"])
            issued[key] = int(r["pf_issued"]) / dem if dem > 0 else 0.0
            hits[key] = int(r["pf_useful_hit"]) / dem if dem > 0 else 0.0
            try:
                ipcs[key] = float(r["ipc"])
            except ValueError:
                ipcs[key] = 0.0
    # per (trace, family, bw): best-IPC degree and its net waste
    best = {}
    for (t, name, bw), ipc in ipcs.items():
        m = re.match(r"^(sandbox|dspatch|mlop|stream)_d\d+$", name)
        if not m:
            continue
        fam_key = (t, m.group(1), bw)
        if fam_key not in best or ipc > best[fam_key][0]:
            best[fam_key] = (ipc, issued[(t, name, bw)] - hits[(t, name, bw)])
    churn = {}
    for (t, name, bw), v in issued.items():
        m = re.match(r"^(sandbox|dspatch|mlop|stream)_d\d+$", name)
        if not m:
            continue
        ref_net = best[(t, m.group(1), bw)][1]
        churn[(t, name, bw)] = max(0.0, (v - hits[(t, name, bw)]) - ref_net)
    return churn


def load_ipc_gaps(csv_path):
    """((trace, stat_name, bw), (trace, bw)) -> 1 - ipc/ipc_best over the 12 candidates.

    Opportunity-cost tax: a policy whose full-trace IPC sits far below the
    trace's best must beat that policy locally by a comparable margin to
    win a PC. This is the cross-family generalization of the churn tax
    (which only compares degrees within one family).

    The second return value is the 'no' gap: 1 - ipc(no)/ipc_best. The OFF
    candidate pays the same opportunity cost as everyone else - giving up
    prefetching costs the IPC gap between no-prefetch and the trace's best
    policy. Without it no would enter untaxed and systematically win PCs
    at low bandwidth (measured: sphinx3@bw1600 lost 12.4% to over-shutoff).
    """
    ipcs = {}
    no_ipcs = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            try:
                v = float(r["ipc"])
            except ValueError:
                continue
            if re.match(r"^(sandbox|dspatch|mlop|stream)_d\d+$", r["prefetcher"]):
                ipcs[(r["trace"], r["prefetcher"], r["bw"])] = v
            elif r["prefetcher"] in ("no_d1", "b0_no"):
                no_ipcs[(r["trace"], r["bw"])] = v
    best = {}
    for (t, name, bw), v in ipcs.items():
        best[(t, bw)] = max(best.get((t, bw), 0.0), v)
    gap = {}
    for (t, name, bw), v in ipcs.items():
        b = best.get((t, bw), 0.0)
        gap[(t, name, bw)] = max(0.0, 1.0 - v / b) if b > 0 else 0.0
    no_gap = {}
    for (t, bw), v in no_ipcs.items():
        b = best.get((t, bw), 0.0)
        no_gap[(t, bw)] = max(0.0, 1.0 - v / b) if b > 0 else 0.0
    return gap, no_gap, ipcs, no_ipcs


L2_LOAD_RE = re.compile(r"^cpu0->cpu0_L2C LOAD\s+ACCESS:\s*(\d+) HIT:\s*(\d+)")


def l2_gaps(bw_dir):
    """(pf, deg) -> L2-pollution tax = max(0, hr_best - hr) over the 12
    candidates' eval files in bw_dir.

    The demand L2 hit rate is a global observable: prefetch pollution that
    evicts demand-needed lines slows every PC's L2 hits, which per-PC AMAT
    structurally cannot see (benefit concentrates in the prefetching PC,
    cost diffuses to everyone). The isolated single-policy runs already
    carry the signature — cactusADM: stream_d1 75.5% vs sandbox 53% — so
    no new experiment is needed, just this parse."""
    hrs = {}
    for fn in os.listdir(bw_dir):
        m = re.match(r"^(sandbox|dspatch|mlop|stream)_d(\d+)\.txt$", fn)
        if not m:
            continue
        pf, deg = m.group(1), int(m.group(2))
        if not is_candidate(pf, deg):
            continue
        try:
            with open(os.path.join(bw_dir, fn), errors="replace") as f:
                for line in f:
                    mm = L2_LOAD_RE.match(line)
                    if mm:
                        acc, hit = int(mm.group(1)), int(mm.group(2))
                        hrs[(pf, deg)] = hit / acc if acc > 0 else None
                        break
        except OSError:
            continue
    best = max((v for v in hrs.values() if v is not None), default=None)
    if best is None:
        return {}
    return {k: max(0.0, best - v) for k, v in hrs.items() if v is not None}


def load_pc_cost(profile_dir):
    """Load per-PC prefetch cost from a profiling dir of <trace>__<pf>__<deg>.json files.
    Returns dict: (pc, "pf:deg") -> waste ratio in [0,1]."""
    fname_re = re.compile(r"(.+?)__(.+?)__(\d+)\.json$")
    cost = {}
    if not profile_dir or not os.path.isdir(profile_dir):
        return cost
    for fn in os.listdir(profile_dir):
        m = fname_re.match(fn)
        if not m:
            continue
        _, pf, deg = m.group(1), m.group(2), int(m.group(3))
        key = f"{pf}:{deg}"
        with open(os.path.join(profile_dir, fn)) as f:
            for line in f:
                line = line.strip()
                if not line.startswith("{"):
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                pc = rec.get("pc", "")
                pc = pc.lower() if isinstance(pc, str) else f"0x{pc:x}"
                issued = int(rec.get("prefetch_issued", 0))
                hit = int(rec.get("prefetch_hit", 0))
                if issued > 0:
                    cost[(pc, key)] = (issued - hit) / issued
    return cost


def load_pc_weights(profile_dir):
    """Per-PC demand weight and useless-prefetch count from a profiling dir
    of <trace>__<pf>__<deg>.json files.

    Returns (weights, useless): pc -> access_count (from the 'no' profile,
    the demand-side reference), and (pc, "pf:deg") -> issued - hit. These
    are the inputs the Pigouvian scheme needs but ground_truth.jsonl
    (AMATs only) does not carry."""
    fname_re = re.compile(r"(.+?)__(.+?)__(\d+)\.json$")
    weights, useless = {}, {}
    if not profile_dir or not os.path.isdir(profile_dir):
        return weights, useless
    for fn in os.listdir(profile_dir):
        m = fname_re.match(fn)
        if not m:
            continue
        pf, deg = m.group(2), int(m.group(3))
        key = f"{pf}:{deg}"
        with open(os.path.join(profile_dir, fn)) as f:
            for line in f:
                line = line.strip()
                if not line.startswith("{"):
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                pc = rec.get("pc", "")
                pc = pc.lower() if isinstance(pc, str) else f"0x{pc:x}"
                if pf == "no":
                    weights[pc] = int(rec.get("access_count", 0))
                useless[(pc, key)] = (int(rec.get("prefetch_issued", 0))
                                      - int(rec.get("prefetch_hit", 0)))
    return weights, useless


def read_hint_bin(path):
    """hint.bin -> {pc: policy index} (12 = OFF sentinel)."""
    import struct
    E = struct.Struct("<QBBBB4x")
    b = open(path, "rb").read()
    _, _, cnt, _ = struct.unpack_from("<IIII", b, 0)
    return {E.unpack_from(b, o)[0]: E.unpack_from(b, o)[2]
            for o in range(16, 16 + cnt * 16, 16)}


def load_mix_records(seg_txt):
    """Per-PC mixed-regime evidence from a hint_eval seg-sim output's
    profile tail: {pc_str: (prefetch_issued, avg_amat)}. Empty when the
    seg sim has not been run (first pass) - the rescue then has no
    jurisdiction and the gate falls back to ledger-only behavior."""
    out = {}
    if not os.path.exists(seg_txt):
        return out
    with open(seg_txt, errors="ignore") as f:
        for line in f:
            if not line.startswith('{"pc"'):
                continue
            r = json.loads(line)
            out[r["pc"]] = (r["prefetch_issued"], r["avg_amat"])
    return out


def seg_ipc(seg_txt):
    """CPU 0 cumulative IPC from a seg-sim output, None if absent."""
    if not os.path.exists(seg_txt):
        return None
    ipc = None
    with open(seg_txt, errors="ignore") as f:
        for line in f:
            m = re.match(r"CPU 0 cumulative IPC:\s*([\d.]+)", line)
            if m:
                ipc = float(m.group(1))
    return ipc


IPC_RE = re.compile(r"cumulative IPC:\s*([\d.]+)")


def global_best(bw_dir):
    """Argmax cumulative IPC over the single-policy eval files in bw_dir.
    Returns (pf, deg) or None."""
    best = None
    best_ipc = 0.0
    for fn in os.listdir(bw_dir):
        m = re.match(r"^(sandbox|dspatch|mlop|stream)_d(\d+)\.txt$", fn)
        if not m:
            continue
        pf, deg = m.group(1), int(m.group(2))
        if not is_candidate(pf, deg):
            continue
        last = None
        try:
            with open(os.path.join(bw_dir, fn), errors="replace") as f:
                for line in f:
                    if "cumulative IPC" in line:
                        last = line
            v = float(IPC_RE.search(last).group(1))
        except (OSError, AttributeError, ValueError):
            continue
        if v > best_ipc:
            best_ipc, best = v, (pf, deg)
    return best


def gen_bin(labels, out_path):
    """labels: list of {"pc","best_prefetch","best_degree"}; write via oracle_gen."""
    tmp = out_path + ".jsonl"
    with open(tmp, "w") as f:
        for rec in labels:
            f.write(json.dumps(rec) + "\n")
    subprocess.run([sys.executable, ORACLE_GEN, "generate", "--labels", tmp, "--output", out_path],
                   check=True, capture_output=True)
    os.remove(tmp)


# ── cell assembly ──

def build_cell(tname, bw, gt, tie_gt, gb_key, acc, nets, wci_sel,
               mix_ev, habitat):
    """CellData with all accessors bound to this (trace, bw)."""
    twaste, churn, ipc_gap, ipc_gap_no, l2g, waste, ipcs, ipc_n = acc
    return CellData(
        tname, bw, gt, tie_gt=tie_gt, gb_key=gb_key,
        twaste=lambda pf, deg: twaste.get((tname, policy_to_stat_name(pf, deg), bw), 0.0),
        churn=lambda pf, deg: churn.get((tname, policy_to_stat_name(pf, deg), bw), 0.0),
        ipc_gap=lambda pf, deg: ipc_gap.get((tname, policy_to_stat_name(pf, deg), bw), 0.0),
        ipc_gap_no=ipc_gap_no.get((tname, bw), 0.0),
        l2_gap=lambda pf, deg: l2g.get((pf, deg), 0.0),
        waste_acc=lambda pf, deg: 0.0 if pf == "no" else waste.get(
            (tname, policy_to_stat_name(pf, deg), bw), 0.0),
        nets=nets,
        toxic=(lambda key: False) if ipc_n is None else (
            lambda key: _is_toxic(key, tname, bw, ipcs, ipc_n)),
        wci_sel=wci_sel, mix_ev=mix_ev, poison_habitat=habitat)


def _is_toxic(key, tname, bw, ipcs, ipc_n):
    """Isolated single-policy run loses to 'no' (dC > 0)."""
    pf, deg = key.rsplit(":", 1)
    ipc_p = ipcs.get((tname, policy_to_stat_name(pf, int(deg)), bw))
    return ipc_p is not None and (1e8 / ipc_p - 1e8 / ipc_n) > 0.0


def run_schemes(schemes, tname, bw, gt_variants, gb_key, acc, pc_w, pc_u,
                ipcs, no_ipcs, wci_bin, seg_dir, out_dir):
    """Generate every requested scheme's bin for one cell.

    gt_variants: {"native": gt_bw, "gt3200": gt3200} - score="oracle"
    selects on gt3200 with the bw-native gt for tie checks (Scheme B);
    everything else selects on the bw-native ground truth.
    Returns {scheme: bin_path}.
    """
    gt_native = gt_variants["native"]
    if not gt_native:
        return {}
    need_nets = any(c["score"] == "pigou" or c["gate"] == "pigou"
                    for _, c in schemes)
    nets = pigou_net(gt_native, pc_w, pc_u, ipcs, no_ipcs, tname, bw) \
        if need_nets else None
    need_rescue = any(c["gate"] == "pigou" and c["pg_mix_rescue"]
                      for _, c in schemes)
    mix_ev, habitat = None, True
    if seg_dir and need_rescue:
        wci_txt = os.path.join(seg_dir, tname, bw, "tax_wci.txt")
        no_txt = os.path.join(seg_dir, tname, bw, "no.txt")
        mix_ev = load_mix_records(wci_txt)
        wci_ipc, no_ipc = seg_ipc(wci_txt), seg_ipc(no_txt)
        if wci_ipc is not None and no_ipc is not None:
            habitat = wci_ipc < no_ipc
    written = {}
    for out_name, cfg in schemes:
        wci_sel = None
        if cfg["gate"] == "pigou" and cfg["base"] == "wci_bin":
            if not os.path.exists(wci_bin):
                continue  # historical behavior: skip when the wci bin is absent
            wci_sel = {f"0x{pc:x}": idx for pc, idx in read_hint_bin(wci_bin).items()}
        if cfg["score"] == "oracle":
            gt, tie_gt = gt_variants["gt3200"], gt_native
        else:
            gt, tie_gt = gt_native, None
        cell = build_cell(tname, bw, gt, tie_gt, gb_key, acc, nets,
                          wci_sel, mix_ev, habitat)
        out = os.path.join(out_dir, out_name)
        gen_bin(make_labels(cell, cfg), out)
        written[out_name] = out
    return written


def parse_args(argv):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run_dir")
    ap.add_argument("stage2_dir")
    ap.add_argument("stats_csv")
    ap.add_argument("cost_base", nargs="?")
    ap.add_argument("seg_dir", nargs="?",
                    help="seg-sim outputs (wci pass) enabling the mixed-regime rescue")
    ap.add_argument("--schemes", default=",".join(DEFAULT_SCHEMES),
                    help="comma-separated preset names (see --list)")
    ap.add_argument("--config", default=None,
                    help="JSON overrides on top of DEFAULT_CONFIG; generates one "
                         "extra bin set named hint_<config-name>.bin")
    ap.add_argument("--config-name", default=None,
                    help="output tag for --config (default: cfg_<hash>)")
    ap.add_argument("--list", action="store_true",
                    help="print PARAM_SPACE and PRESETS as JSON and exit")
    return ap.parse_args(argv)


def main():
    args = parse_args(sys.argv[1:])
    if args.list:
        print(json.dumps({
            "param_space": [{"name": n, "kind": k, "bounds": b, "default": d}
                            for n, k, b, d in PARAM_SPACE],
            "default_config": DEFAULT_CONFIG,
            "presets": PRESETS,
        }, indent=2))
        return

    schemes = []
    for name in args.schemes.split(","):
        name = name.strip()
        if not name:
            continue
        if name not in PRESETS:
            sys.exit(f"unknown scheme {name!r} (see --list)")
        schemes.append((name, SCHEME_OUT.get(name, f"hint_tax_{name}.bin"),
                        PRESETS[name]))
    if args.config:
        overrides = json.loads(args.config)
        unknown = set(overrides) - set(DEFAULT_CONFIG)
        if unknown:
            sys.exit(f"unknown config keys: {sorted(unknown)} (see --list)")
        cfg = dict(DEFAULT_CONFIG)
        cfg.update(overrides)
        tag = args.config_name or f"cfg_{config_slug(cfg)}"
        schemes.append((tag, f"hint_{tag}.bin", cfg))

    run_dir, stage2_dir, stats_csv = args.run_dir, args.stage2_dir, args.stats_csv
    seg_dir = args.seg_dir
    waste = load_waste(stats_csv)  # accuracy-based: gate scheme
    demand_by_trace = {tname: load_demand_total(os.path.join(stage2_dir, tname, "profiling"))
                       for tname in os.listdir(stage2_dir)}
    twaste = load_traffic_waste(stats_csv, demand_by_trace)  # traffic-based: tax schemes
    churn = load_churn(stats_csv, demand_by_trace)  # pipeline-occupancy tax: degree selection
    ipc_gap, ipc_gap_no, ipcs, no_ipcs = load_ipc_gaps(stats_csv)  # opportunity-cost tax

    for tname in sorted(os.listdir(run_dir)):
        tdir = os.path.join(run_dir, tname)
        if not os.path.isdir(tdir):
            continue
        gt3200 = load_ground_truth(os.path.join(stage2_dir, tname, "ground_truth.jsonl"))
        pc_w, pc_u = load_pc_weights(os.path.join(stage2_dir, tname, "profiling"))

        for bw in ("bw1600", "bw800"):
            bw_dir = os.path.join(tdir, bw)
            gt_native = load_ground_truth(os.path.join(bw_dir, "ground_truth.jsonl"))
            if not gt_native:
                continue
            gb = global_best(bw_dir) or GATE_FALLBACK  # this bw's offline global best
            gb_key = f"{gb[0]}:{gb[1]}"
            acc = (twaste, churn, ipc_gap, ipc_gap_no, l2_gaps(bw_dir),
                   waste, ipcs, no_ipcs.get((tname, bw)))
            cell_schemes = [(out, cfg) for _, out, cfg in schemes]
            written = run_schemes(
                cell_schemes, tname, bw,
                {"native": gt_native, "gt3200": gt3200}, gb_key, acc,
                pc_w, pc_u, ipcs, no_ipcs,
                os.path.join(bw_dir, "hint_tax_wci.bin"), seg_dir, bw_dir)
            if SCHEME_OUT["gate_t90"] in written:
                # quick distribution summary: lowest-tier (conservative) share
                sel = read_hint_bin(written[SCHEME_OUT["gate_t90"]])
                low = sum(1 for idx in sel.values()
                          if idx_to_key(idx).rsplit(":", 1)[1]
                          == str(min(CANDIDATE_FAMILIES[idx_to_key(idx).rsplit(":", 1)[0]]))
                          and idx < 12)
                print(f"{tname} {bw}: lowest-tier share = "
                      f"{100*low/max(len(sel),1):.0f}% of {len(sel)} PCs")

        # ── bw3200: the tax schemes apply at native bandwidth too (the
        # per-PC AMAT vs global IPC misalignment exists at 3200 - mcf's
        # dspatch wins per-PC AMAT but floods the channel). Tied PCs get
        # the trace-wide best without tax.
        eval_dir = os.path.join(stage2_dir, tname, "eval")
        if not os.path.isdir(eval_dir):
            continue
        gb3200 = global_best(eval_dir) or GATE_FALLBACK
        gb_key = f"{gb3200[0]}:{gb3200[1]}"
        acc = (twaste, churn, ipc_gap, ipc_gap_no, l2_gaps(eval_dir),
               waste, ipcs, no_ipcs.get((tname, "bw3200")))
        cell_schemes = [(out, cfg) for name, out, cfg in schemes
                        if name not in NO_3200]
        run_schemes(
            cell_schemes, tname, "bw3200",
            {"native": gt3200, "gt3200": gt3200}, gb_key, acc,
            pc_w, pc_u, ipcs, no_ipcs,
            os.path.join(stage2_dir, tname, "hint_tax_wci.bin"), seg_dir,
            os.path.join(stage2_dir, tname))


if __name__ == "__main__":
    main()
